---
title: Andrew.
copyright: ©2010-2018 Marc Andrew Harter

baseURL: http://wavded.com
buildDrafts: true
disableHugoGeneratorInject: true
pygmentsCodeFences: true
pygmentsStyle: manni
footnoteReturnLinkContents: "↩"
metaDataFormat: "yaml"

params:
  githubURL: https://github.com/wavded/www
